### ISSUE TITLE
Merge queries like with mod_rewrite's QSA flag

### ISSUE THREAD

**Issue by santillaner** [kapouer/express-urlrewrite#2]
Hi there, 

Is there a way to merge queries like Apache's mod_rewrite QSA flag (query string append)?

https://httpd.apache.org/docs/2.4/rewrite/flags.html#flag_qsa

cheers

**Comment by kapouer** [comment]
No, https://github.com/kapouer/express-urlrewrite/blob/e7728920eb7f770e4296453f22638050cc3e017e/index.js#L57 overwrites query object.

Pull requests are welcome, though keep in mind it must be backward-compatible, and that i'm more interested in a PR that sets up tests right now...

**Comment by kapouer** [comment]
As far i as understand, "qsa" flag is not needed in that module.
