### ISSUE TITLE
How would I rewrite a URL disregarding the query?

### ISSUE THREAD

**Issue by AaronBeaudoin** [kapouer/express-urlrewrite#7]
I want to match a path starting with `/some/path` whether or not it has a trailing slash (or a sub route), and ignores the query, simply copying it to the new path unchanged.

```
/some/path          --> /other/path
/some/path/         --> /other/path/
/some/path?a=b      --> /other/path?a=b
/some/path/?a=b     --> /other/path/?a=b
/some/path/sub      --> /other/path/sub
/some/path/sub/     --> /other/path/sub/
/some/path/sub?a=b  --> /other/path/sub?a=b
/some/path/sub/?a=b --> /other/path/sub/?a=b
```

I can't find a value that does this when I pass it.

**Comment by AaronBeaudoin** [comment]
As a temporary solution right now I'm doing this (but I don't know if there are weird edge cases that would break it):

```js
function replaceMiddleware(expression, replacement) {
  return (request, response, next) => {
    request.url = request.originalUrl = request.originalUrl.replace(expression, replacement);
    next();
  };
}

app.use(replaceMiddleware(/^\/some\/path/, "/other/path"));
```

I also can't help but think `express-urlrewrite` should be able to give me an easy way to do this same thing, but I just can't seem to figure out how.

**Comment by kapouer** [comment]
There are a lot of things that are not right in my middleware: use your solution, it'll be easier to maintain in your project.
